package com.kms.DataObject;


import com.kms.Dao.UserDOMapper;

public class UserDO  {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.CustomerID
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    private String customerid;
    private String customername;
    private String customershortname;
    private String pycode;
    private String contactname;
    private String contacttitle;
    private String employeeid;
    private String address;
    private String cityid;
    private String provinceid;
    private String zip;
    private String phone;
    private String fax;
    private String email;
    private String homepage;
    private String bankname;
    private String bankaccount;
    private String certificateno;
    private String eowner;
    private String taxpayerno;
    private String filepath;
    private String filename;
    private String categoryid;
    private String notes;

    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.CustomerID
     *
     * @param customerid the value for customers.CustomerID
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.CustomerName
     *
     * @return the value of customers.CustomerName
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.CustomerName
     *
     * @param customername the value for customers.CustomerName
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.CustomerShortName
     *
     * @return the value of customers.CustomerShortName
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getCustomershortname() {
        return customershortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.CustomerShortName
     *
     * @param customershortname the value for customers.CustomerShortName
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setCustomershortname(String customershortname) {
        this.customershortname = customershortname == null ? null : customershortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.pyCode
     *
     * @return the value of customers.pyCode
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getPycode() {
        return pycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.pyCode
     *
     * @param pycode the value for customers.pyCode
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setPycode(String pycode) {
        this.pycode = pycode == null ? null : pycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Contactname
     *
     * @return the value of customers.Contactname
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Contactname
     *
     * @param contactname the value for customers.Contactname
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Contacttitle
     *
     * @return the value of customers.Contacttitle
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getContacttitle() {
        return contacttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Contacttitle
     *
     * @param contacttitle the value for customers.Contacttitle
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setContacttitle(String contacttitle) {
        this.contacttitle = contacttitle == null ? null : contacttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.EmployeeID
     *
     * @return the value of customers.EmployeeID
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.EmployeeID
     *
     * @param employeeid the value for customers.EmployeeID
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid == null ? null : employeeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Address
     *
     * @return the value of customers.Address
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Address
     *
     * @param address the value for customers.Address
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.CityID
     *
     * @return the value of customers.CityID
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.CityID
     *
     * @param cityid the value for customers.CityID
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.ProvinceID
     *
     * @return the value of customers.ProvinceID
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.ProvinceID
     *
     * @param provinceid the value for customers.ProvinceID
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Zip
     *
     * @return the value of customers.Zip
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Zip
     *
     * @param zip the value for customers.Zip
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Phone
     *
     * @return the value of customers.Phone
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Phone
     *
     * @param phone the value for customers.Phone
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Fax
     *
     * @return the value of customers.Fax
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Fax
     *
     * @param fax the value for customers.Fax
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Email
     *
     * @return the value of customers.Email
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Email
     *
     * @param email the value for customers.Email
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.HomePage
     *
     * @return the value of customers.HomePage
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.HomePage
     *
     * @param homepage the value for customers.HomePage
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage == null ? null : homepage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Bankname
     *
     * @return the value of customers.Bankname
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Bankname
     *
     * @param bankname the value for customers.Bankname
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Bankaccount
     *
     * @return the value of customers.Bankaccount
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getBankaccount() {
        return bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Bankaccount
     *
     * @param bankaccount the value for customers.Bankaccount
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount == null ? null : bankaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.certificateno
     *
     * @return the value of customers.certificateno
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getCertificateno() {
        return certificateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.certificateno
     *
     * @param certificateno the value for customers.certificateno
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setCertificateno(String certificateno) {
        this.certificateno = certificateno == null ? null : certificateno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.eowner
     *
     * @return the value of customers.eowner
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getEowner() {
        return eowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.eowner
     *
     * @param eowner the value for customers.eowner
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setEowner(String eowner) {
        this.eowner = eowner == null ? null : eowner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Taxpayerno
     *
     * @return the value of customers.Taxpayerno
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getTaxpayerno() {
        return taxpayerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Taxpayerno
     *
     * @param taxpayerno the value for customers.Taxpayerno
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setTaxpayerno(String taxpayerno) {
        this.taxpayerno = taxpayerno == null ? null : taxpayerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Filepath
     *
     * @return the value of customers.Filepath
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Filepath
     *
     * @param filepath the value for customers.Filepath
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Filename
     *
     * @return the value of customers.Filename
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Filename
     *
     * @param filename the value for customers.Filename
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.CategoryId
     *
     * @return the value of customers.CategoryId
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.CategoryId
     *
     * @param categoryid the value for customers.CategoryId
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setCategoryid(String categoryid) {
        this.categoryid = categoryid == null ? null : categoryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.Notes
     *
     * @return the value of customers.Notes
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.Notes
     *
     * @param notes the value for customers.Notes
     *
     * @mbg.generated Tue Oct 08 14:27:36 CST 2019
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}